<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '两次密码不一致！' => 'The passwords are inconsistent twice!',
    '原密码' => 'Original password',
    '原密码不正确' => 'The original password is incorrect',
    '密码' => 'Password',
    '帐号' => 'Accounts',
    '帐号或密码不正确.' => 'Account or password incorrect.',
    '新密码' => 'New password',
    '用户不存在' => 'User does not exist',
    '用户名' => 'User name',
    '用户未设置' => 'User not set',
    '登录前请先阅读并同意条款' => 'Please read and agree to the terms before logging in',
    '记住密码' => 'Remember password',
    '重复密码' => 'Repeat password',
    '验证码' => 'Verification Code',
];
