<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '如果您的浏览器没有自动跳转，请点击此链接' => 'If your browser does not automatically redirect, please click on this link',
    '抱歉，站点已暂停' => 'Sorry, the site has been paused',
    '点击这里返回上一页' => 'Click here to return to the previous page',
    '点击这里返回首页' => 'Click here to return to the homepage',
    '系统提示' => 'System prompt',
];
