<?php
/**
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

namespace app\modules\admin\assets;

use yii\bootstrap\BootstrapAsset;
use yii\bootstrap\BootstrapPluginAsset;
use yii\web\AssetBundle;

/**
 * Main application asset bundle.
 *
 * @author Qiang Xue <qiang.xue@gmail.com>
 * @since 2.0
 */
class AdminAsset extends AssetBundle
{
    public $basePath = '@webroot/static/admin';
    public $baseUrl = '@web/static/admin';
    public $css = [
        'css/plugin.min.css',
        'css/style.css',
        'css/x-sure.css',
        'https://cdn.bootcdn.net/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css',
    ];
    public $depends = [
        'yii\web\YiiAsset',
        'app\assets\LayerAsset',
        'app\assets\PluginAsset',
        BootstrapPluginAsset::class
    ];

    public function registerAssetFiles($view)
    {
        $js = <<<JS
$('.nav-item .has-next > a').click(function (e) {
    var li = $(this).parent();
    li.find('ul').stop().slideToggle();
    li.toggleClass('active');
    return false;
})
JS;
        $view->registerJs($js);
        parent::registerAssetFiles($view); // TODO: Change the autogenerated stub
    }
}
