<?php
/**
 * Created by zsz
 * User zsz
 * Time: 2024/1/10 13:31
 */
namespace app\assets;

use yii\web\AssetBundle;

class PluginAsset extends AssetBundle
{
    public $basePath = '@webroot/static/plugins';
    public $baseUrl = '@web/static/plugins';

    public $css = [
        'fancybox/jquery.fancybox.min.css',
        'layui/css/layui.css',
    ];

    public $js = [
        'jsBarcode/JsBarcode.all.min.js', //条形码
        'jquery-qrcode/jquery.qrcode.min.js', //二维码
        'clipboard/clipboard.js', //复制
        'sweetalert/sweetalert.min.js', //美化 原生的 alert等函数
        'fancybox/jquery.fancybox.min.js', //图片查看
        'layui/layui.js',
        'layui/layui-config.js',
    ];

    public function registerAssetFiles($view)
    {
        $js = <<<JS
$(document).ready(function() {
  $('a.fancybox').fancybox({
        'transitionIn'  :   'elastic',
        'transitionOut' :   'elastic',
        'speedIn'       :   600, 
        'speedOut'      :   200, 
        'overlayShow'   :   false
  })

    //复制
   var clipboard = new ClipboardJS('.btn-clip');

    clipboard.on('success', function(e) {
        e.clearSelection();
        layer.msg('复制成功', {icon: 1});
    });

    clipboard.on('error', function(e) {
        layer.msg('复制失败', {icon: 5});
    });
    
    //二维码
    $('.generateCode').each(function() {
       let ele = $('<div>')
       ele.qrcode({ 
            render: "table", //table方式 
            width: 200, //宽度 
            height:200, //高度 
            text: $(this).attr('data-text') //任意内容 
       });
       $(this).append(ele)
    })
    
    // swal 使用
    $('.delete').click(function() {
     swal({
        title: '操作成功',
        icon: "success",
        button: "确定",
    });
    })
})
JS;
        $view->registerJs($js);
        parent::registerAssetFiles($view); // TODO: Change the autogenerated stub
    }
}